// <auto-generated />
using System;
using Cw7.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cw7.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260519230647_fixDateTimeErrorAndSeed")]
    partial class fixDateTimeErrorAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cw7.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "abc1",
                            ComponentManufacturersId = 5,
                            ComponentTypesId = 2,
                            Description = "flagship gpu",
                            Name = "RTX4090"
                        },
                        new
                        {
                            Code = "abc2",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 2,
                            Description = "dedicated intel gpu",
                            Name = "ArcB580"
                        },
                        new
                        {
                            Code = "abc3",
                            ComponentManufacturersId = 5,
                            ComponentTypesId = 1,
                            Description = "flagship intel consumer cpu",
                            Name = "ultra 9"
                        },
                        new
                        {
                            Code = "abc4",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 1,
                            Description = "Apple silicon cpu",
                            Name = "M5"
                        },
                        new
                        {
                            Code = "abc5",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 3,
                            Description = "Great gaming motherboard",
                            Name = "super gaming mobo"
                        },
                        new
                        {
                            Code = "abc6",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 3,
                            Description = "budget motherboard",
                            Name = "epic shadow mobo"
                        });
                });

            modelBuilder.Entity("Cw7.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "MSI",
                            FoundationDate = new DateTime(1986, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Micro-Star-International"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "Apple",
                            FoundationDate = new DateTime(1976, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Apple Inc."
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "Asus",
                            FoundationDate = new DateTime(1989, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Asus Inc."
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Intel",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Inc."
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "Nvidia",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nvidia Inc."
                        });
                });

            modelBuilder.Entity("Cw7.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "cpu",
                            Name = "Central processing unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "gpu",
                            Name = "Graphics processing unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "mobo",
                            Name = "Mother Board"
                        });
                });

            modelBuilder.Entity("Cw7.Models.PCComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int")
                        .HasColumnName("PCId");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "abc5",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "abc3",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "abc1",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "abc6",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "abc2",
                            Amount = 0
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "abc3",
                            Amount = 0
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "abc4",
                            Amount = 0
                        });
                });

            modelBuilder.Entity("Cw7.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Macbook pro",
                            Stock = 1,
                            Warranty = 12,
                            Weight = 1.55f
                        });
                });

            modelBuilder.Entity("Cw7.Models.Component", b =>
                {
                    b.HasOne("Cw7.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cw7.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Cw7.Models.PCComponent", b =>
                {
                    b.HasOne("Cw7.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cw7.Models.Pc", "PCs")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PCs");
                });

            modelBuilder.Entity("Cw7.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("Cw7.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Cw7.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Cw7.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
